### ISSUE TITLE
New ELUT are not the same format as old one 

### ISSUE THREAD

**Issue by samaloney** [i4Ds/STIX-CONF#12]
See

https://raw.githubusercontent.com/i4Ds/STIX-CONF/main/elut/elut_table_20231019.csv

vs

https://raw.githubusercontent.com/i4Ds/STIX-CONF/main/elut/elut_table_20240205.csv

@drhlxiao can these be formatted in the same way?

**Comment by drhlxiao** [comment]
The double quotes have been removed from the file. Could you replace the one with this one:  
https://datacenter.stix.i4ds.net/pub/misc/stix-config/elut/elut_table_20240205.csv

I also updated the elut creator  https://datacenter.stix.i4ds.net/pub/misc/stix-config/tools/
It won't include quotes for numbers anymore. 
@samaloney

**Comment by samaloney** [comment]
Great thanks @drhlxiao
